import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import AppShell from "@/components/AppShell";
import api from "@/lib/api";
import { ArrowLeft, ArrowUp, ArrowDown, Share2, Loader2, Film, Sparkles } from "lucide-react";
import { toast } from "sonner";

export default function ReelsPage() {
  const { id } = useParams();
  const [reels, setReels] = useState([]);
  const [idx, setIdx] = useState(0);
  const [busy, setBusy] = useState(false);
  const [setTitle, setSetTitle] = useState("");
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    api.get(`/study-sets/${id}`).then(({ data }) => setSetTitle(data.title)).catch(() => {});
    api.get(`/reels/${id}`).then(({ data }) => {
      setReels(data.reels || []);
      setLoaded(true);
    }).catch(() => setLoaded(true));
  }, [id]);

  const generate = async () => {
    setBusy(true);
    try {
      const { data } = await api.post("/reels/generate", { study_set_id: id });
      setReels(data.reels || []);
      setIdx(0);
      toast.success(`${data.reels?.length || 0} reels ready!`);
    } catch (e) {
      toast.error(e?.response?.data?.detail || "Failed to generate");
    } finally {
      setBusy(false);
    }
  };

  const next = () => idx + 1 < reels.length && setIdx(idx + 1);
  const prev = () => idx > 0 && setIdx(idx - 1);

  const share = (r) => {
    const text = `📚 ${r.title}\n\n${r.script_text || (r.hook + "\n" + (r.points || []).join("\n") + "\n" + r.takeaway)}\n\nGenerated by StudyPilot`;
    if (navigator.clipboard) {
      navigator.clipboard.writeText(text);
      toast.success("Copied to clipboard — paste into WhatsApp!");
    }
  };

  return (
    <AppShell>
      <div className="p-10 max-w-7xl">
        <Link to={`/study-set/${id}`} className="inline-flex items-center gap-2 text-white/60 hover:text-white mb-6 text-sm">
          <ArrowLeft className="w-4 h-4" /> Back
        </Link>
        <div className="mb-8 flex items-end justify-between">
          <div>
            <p className="text-xs uppercase tracking-[0.3em] text-[#f5a623] mb-2 flex items-center gap-2"><Film className="w-3 h-3" /> Micro Reels</p>
            <h1 className="font-heading font-extrabold text-4xl">{setTitle}</h1>
            <p className="text-white/60 mt-2">Bite-sized concept videos. Swipe through. Share to WhatsApp.</p>
          </div>
          {reels.length > 0 && (
            <button onClick={generate} disabled={busy} data-testid="regenerate-reels-btn" className="px-5 py-2.5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition text-white text-sm">
              Regenerate
            </button>
          )}
        </div>

        {!loaded ? (
          <div className="flex items-center justify-center py-32 text-white/60">
            <Loader2 className="w-6 h-6 animate-spin mr-3" /> Loading...
          </div>
        ) : reels.length === 0 ? (
          <div className="bg-[#111118] border border-white/5 rounded-2xl p-16 text-center">
            <Film className="w-12 h-12 text-white/20 mx-auto mb-4" />
            <h3 className="font-heading font-bold text-2xl mb-2">No reels yet</h3>
            <p className="text-white/50 mb-6">Generate 5 micro-learning reels from your study set.</p>
            <button
              onClick={generate}
              disabled={busy}
              data-testid="generate-reels-btn"
              className="px-7 py-3.5 rounded-xl bg-gradient-to-r from-[#4f6ef7] to-[#f5a623] text-white font-medium hover:shadow-[0_0_30px_rgba(245,166,35,0.4)] transition-all disabled:opacity-50 inline-flex items-center gap-2"
            >
              {busy ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
              Generate Reels
            </button>
          </div>
        ) : (
          <div className="flex items-center justify-center gap-6">
            {/* Up */}
            <button onClick={prev} disabled={idx === 0} data-testid="reel-prev" className="p-3 rounded-full bg-white/5 border border-white/10 hover:bg-white/10 disabled:opacity-30 transition">
              <ArrowUp className="w-5 h-5" />
            </button>

            {/* Reel card */}
            <ReelCard reel={reels[idx]} idx={idx} total={reels.length} onShare={() => share(reels[idx])} />

            {/* Down */}
            <button onClick={next} disabled={idx + 1 >= reels.length} data-testid="reel-next" className="p-3 rounded-full bg-white/5 border border-white/10 hover:bg-white/10 disabled:opacity-30 transition">
              <ArrowDown className="w-5 h-5" />
            </button>
          </div>
        )}
      </div>
    </AppShell>
  );
}

function ReelCard({ reel, idx, total, onShare }) {
  if (!reel) return null;
  return (
    <div
      className="relative w-[390px] h-[693px] rounded-3xl overflow-hidden bg-gradient-to-b from-[#1a1a2a] via-[#111118] to-[#0a0a0f] border border-white/10 shadow-[0_0_60px_rgba(79,110,247,0.2)]"
      data-testid={`reel-card-${idx}`}
    >
      {/* Top gradient strip */}
      <div className="absolute top-0 inset-x-0 h-1 bg-gradient-to-r from-[#4f6ef7] via-[#00c4cc] to-[#f5a623]" />
      <div className="absolute top-4 right-4 px-2.5 py-1 rounded-full bg-black/40 backdrop-blur text-white/80 text-xs font-mono">
        {idx + 1} / {total}
      </div>

      <div className="p-8 pt-12 h-full flex flex-col">
        <p className="text-xs uppercase tracking-[0.3em] text-[#f5a623] mb-3">Concept</p>
        <h2 className="font-heading font-extrabold text-3xl text-white mb-5 leading-tight">{reel.title}</h2>

        <div className="bg-white/5 border border-white/10 rounded-2xl p-4 mb-4">
          <p className="text-white/90 italic text-sm leading-relaxed">"{reel.hook}"</p>
        </div>

        <ul className="space-y-2.5 mb-4 flex-1">
          {(reel.points || []).map((p, i) => (
            <li key={i} className="flex items-start gap-2 text-white/85 text-sm leading-relaxed">
              <span className="text-[#00c4cc] font-bold">{i + 1}.</span> {p}
            </li>
          ))}
        </ul>

        {reel.analogy && (
          <div className="bg-[#4f6ef7]/10 border border-[#4f6ef7]/30 rounded-xl p-3 mb-3">
            <p className="text-[10px] uppercase tracking-widest text-[#4f6ef7] mb-1">Analogy</p>
            <p className="text-white/90 text-xs leading-relaxed">{reel.analogy}</p>
          </div>
        )}

        <div className="bg-gradient-to-r from-[#f5a623]/15 to-[#00c4cc]/10 border border-[#f5a623]/30 rounded-xl p-3 mb-3">
          <p className="text-[10px] uppercase tracking-widest text-[#f5a623] mb-1">Takeaway</p>
          <p className="text-white font-semibold text-sm leading-snug">{reel.takeaway}</p>
        </div>

        <button
          onClick={onShare}
          data-testid={`reel-share-${idx}`}
          className="mt-auto w-full py-3 rounded-xl bg-white text-[#0a0a0f] font-medium hover:bg-white/90 transition flex items-center justify-center gap-2"
        >
          <Share2 className="w-4 h-4" /> Share to WhatsApp
        </button>
      </div>
    </div>
  );
}
