import { useEffect, useRef, useState } from "react";
import { useParams, Link } from "react-router-dom";
import AppShell from "@/components/AppShell";
import api from "@/lib/api";
import { ArrowLeft, ChevronUp, ChevronDown, Share2, Loader2, Film, Sparkles, Volume2, VolumeX, Play } from "lucide-react";
import { toast } from "sonner";
import { speak, cancelSpeech, cleanTextForTTS } from "@/lib/tts";

const GRADIENTS = [
  "linear-gradient(180deg, #1a1a2e 0%, #4f6ef7 100%)",
  "linear-gradient(180deg, #0d1117 0%, #00c4cc 100%)",
  "linear-gradient(180deg, #1a0a2e 0%, #f5a623 100%)",
  "linear-gradient(180deg, #0a1628 0%, #e94560 100%)",
  "linear-gradient(180deg, #0a2818 0%, #00c4cc 100%)",
];

export default function ReelsPage() {
  const { id } = useParams();
  const [reels, setReels] = useState([]);
  const [idx, setIdx] = useState(0);
  const [busy, setBusy] = useState(false);
  const [setTitle, setSetTitle] = useState("");
  const [loaded, setLoaded] = useState(false);
  const [muted, setMuted] = useState(false);
  const [showPlayHint, setShowPlayHint] = useState(false);
  const wheelLock = useRef(false);
  const touchStart = useRef(null);

  useEffect(() => {
    api.get(`/study-sets/${id}`).then(({ data }) => setSetTitle(data.title)).catch(() => {});
    api.get(`/reels/${id}`).then(({ data }) => {
      setReels(data.reels || []);
      setLoaded(true);
    }).catch(() => setLoaded(true));
    return () => cancelSpeech();
  }, [id]);

  // Narrate when active reel changes
  useEffect(() => {
    cancelSpeech();
    if (muted || reels.length === 0 || !reels[idx]) return;
    const r = reels[idx];
    const narration = `${r.title}. ${r.hook}. ${(r.points || []).join(". ")}. ${r.takeaway}`;
    const t = setTimeout(() => {
      speak(narration, { lang: "en-US", rate: 0.95, pitch: 1.0 });
    }, 600); // slight delay to allow animation
    return () => { clearTimeout(t); cancelSpeech(); };
  }, [idx, reels, muted]);

  // Keyboard navigation
  useEffect(() => {
    const onKey = (e) => {
      if (e.key === "ArrowDown" || e.key === "ArrowRight") next();
      else if (e.key === "ArrowUp" || e.key === "ArrowLeft") prev();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
    // eslint-disable-next-line
  }, [reels, idx]);

  const generate = async () => {
    setBusy(true);
    try {
      const { data } = await api.post("/reels/generate", { study_set_id: id });
      setReels(data.reels || []);
      setIdx(0);
      toast.success(`${data.reels?.length || 0} reels ready!`);
    } catch (e) {
      toast.error(e?.response?.data?.detail || "Failed to generate");
    } finally {
      setBusy(false);
    }
  };

  const next = () => idx + 1 < reels.length && setIdx(idx + 1);
  const prev = () => idx > 0 && setIdx(idx - 1);

  const onWheel = (e) => {
    if (wheelLock.current) return;
    if (Math.abs(e.deltaY) < 30) return;
    wheelLock.current = true;
    if (e.deltaY > 0) next();
    else prev();
    setTimeout(() => { wheelLock.current = false; }, 500);
  };

  const onTouchStart = (e) => { touchStart.current = e.touches[0].clientY; };
  const onTouchEnd = (e) => {
    if (touchStart.current == null) return;
    const dy = e.changedTouches[0].clientY - touchStart.current;
    if (Math.abs(dy) > 60) {
      if (dy < 0) next(); else prev();
    }
    touchStart.current = null;
  };

  const tap = () => {
    setShowPlayHint(true);
    setTimeout(() => setShowPlayHint(false), 1000);
  };

  const share = (r) => {
    const text = `📚 ${r.title}\n\n${cleanTextForTTS((r.script_text || (r.hook + "\n" + (r.points || []).join("\n") + "\n" + r.takeaway)))}\n\nGenerated by StudyPilot`;
    if (navigator.clipboard) {
      navigator.clipboard.writeText(text);
      toast.success("Copied — paste into WhatsApp!");
    }
  };

  return (
    <AppShell>
      <div className="p-10 max-w-7xl">
        <Link to={`/study-set/${id}`} className="inline-flex items-center gap-2 text-white/60 hover:text-white mb-6 text-sm">
          <ArrowLeft className="w-4 h-4" /> Back
        </Link>
        <div className="mb-8 flex items-end justify-between">
          <div>
            <p className="text-xs uppercase tracking-[0.3em] text-[#f5a623] mb-2 flex items-center gap-2"><Film className="w-3 h-3" /> Micro Reels</p>
            <h1 className="font-heading font-extrabold text-4xl">{setTitle}</h1>
            <p className="text-white/60 mt-2">Swipe up/down · Arrow keys · Scroll wheel</p>
          </div>
          {reels.length > 0 && (
            <button onClick={generate} disabled={busy} data-testid="regenerate-reels-btn" className="px-5 py-2.5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition text-white text-sm">
              Regenerate
            </button>
          )}
        </div>

        {!loaded ? (
          <div className="flex items-center justify-center py-32 text-white/60">
            <Loader2 className="w-6 h-6 animate-spin mr-3" /> Loading...
          </div>
        ) : reels.length === 0 ? (
          <div className="bg-[#111118] border border-white/5 rounded-2xl p-16 text-center">
            <Film className="w-12 h-12 text-white/20 mx-auto mb-4" />
            <h3 className="font-heading font-bold text-2xl mb-2">No reels yet</h3>
            <p className="text-white/50 mb-6">Generate 5 micro-learning reels from your study set.</p>
            <button
              onClick={generate}
              disabled={busy}
              data-testid="generate-reels-btn"
              className="px-7 py-3.5 rounded-xl bg-gradient-to-r from-[#4f6ef7] to-[#f5a623] text-white font-medium hover:shadow-[0_0_30px_rgba(245,166,35,0.4)] transition-all disabled:opacity-50 inline-flex items-center gap-2"
            >
              {busy ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
              Generate Reels
            </button>
          </div>
        ) : (
          <div className="flex items-center justify-center gap-6">
            <button onClick={prev} disabled={idx === 0} data-testid="reel-prev" className="p-3 rounded-full bg-white/5 border border-white/10 hover:bg-white/10 disabled:opacity-30 transition">
              <ChevronUp className="w-5 h-5" />
            </button>

            <div
              onWheel={onWheel}
              onTouchStart={onTouchStart}
              onTouchEnd={onTouchEnd}
              onClick={tap}
              className="relative"
              data-testid="reel-stage"
            >
              <ReelCard
                key={reels[idx].id}
                reel={reels[idx]}
                idx={idx}
                total={reels.length}
                gradient={GRADIENTS[idx % GRADIENTS.length]}
                muted={muted}
                onMute={(e) => { e.stopPropagation(); setMuted((m) => !m); }}
                onShare={(e) => { e.stopPropagation(); share(reels[idx]); }}
              />
              {showPlayHint && (
                <div className="absolute inset-0 flex items-center justify-center pointer-events-none animate-fade-up">
                  <div className="w-20 h-20 rounded-full bg-white/15 backdrop-blur flex items-center justify-center">
                    <Play className="w-10 h-10 text-white fill-white" />
                  </div>
                </div>
              )}
            </div>

            <button onClick={next} disabled={idx + 1 >= reels.length} data-testid="reel-next" className="p-3 rounded-full bg-white/5 border border-white/10 hover:bg-white/10 disabled:opacity-30 transition">
              <ChevronDown className="w-5 h-5" />
            </button>
          </div>
        )}
      </div>
    </AppShell>
  );
}

function ReelCard({ reel, idx, total, gradient, muted, onMute, onShare }) {
  const [hookTyped, setHookTyped] = useState("");
  const [pointsShown, setPointsShown] = useState(0);

  // Reset and animate on reel change
  useEffect(() => {
    setHookTyped("");
    setPointsShown(0);
    let i = 0;
    const text = reel.hook || "";
    const typer = setInterval(() => {
      i++;
      setHookTyped(text.slice(0, i));
      if (i >= text.length) clearInterval(typer);
    }, 50);
    // Stagger points
    const timers = [];
    (reel.points || []).forEach((_, k) => {
      timers.push(setTimeout(() => setPointsShown((p) => Math.max(p, k + 1)), 800 * (k + 1) + text.length * 50));
    });
    return () => {
      clearInterval(typer);
      timers.forEach(clearTimeout);
    };
  }, [reel]);

  return (
    <div
      key={reel.id}
      className="relative w-[390px] h-[693px] rounded-3xl overflow-hidden border border-white/10 shadow-[0_0_60px_rgba(79,110,247,0.3)] reel-enter"
      style={{ background: gradient }}
      data-testid={`reel-card-${idx}`}
    >
      {/* Top strip + counter + mute */}
      <div className="absolute top-0 inset-x-0 h-1 bg-gradient-to-r from-white/40 via-white/80 to-white/40" />
      <div className="absolute top-4 left-4 right-4 flex items-center justify-between z-10">
        <span className="px-2.5 py-1 rounded-full bg-black/40 backdrop-blur text-white/80 text-xs font-mono">{idx + 1} / {total}</span>
        <button onClick={onMute} data-testid={`reel-mute-${idx}`} className="p-2 rounded-full bg-black/40 backdrop-blur hover:bg-black/60 transition">
          {muted ? <VolumeX className="w-4 h-4 text-white" /> : <Volume2 className="w-4 h-4 text-white" />}
        </button>
      </div>

      <div className="p-7 pt-14 h-full flex flex-col">
        <p className="text-[10px] uppercase tracking-[0.3em] text-white/70 mb-2">Concept</p>
        <h2 className="font-heading font-extrabold text-2xl text-white mb-4 leading-tight drop-shadow">{reel.title}</h2>

        <div className="bg-white/15 backdrop-blur border border-white/20 rounded-2xl p-4 mb-4 min-h-[68px]">
          <p className="text-white text-base font-semibold leading-snug">"{hookTyped}<span className="opacity-60 animate-pulse">{hookTyped.length < (reel.hook || "").length ? "▎" : ""}</span>"</p>
        </div>

        <ul className="space-y-2.5 mb-3 flex-1">
          {(reel.points || []).map((p, i) => (
            <li
              key={i}
              className="flex items-start gap-2 text-white/95 text-sm leading-relaxed transition-all duration-500"
              style={{
                opacity: i < pointsShown ? 1 : 0,
                transform: i < pointsShown ? "translateY(0)" : "translateY(8px)",
              }}
            >
              <span className="font-bold text-white/80">{i + 1}.</span> {p}
            </li>
          ))}
        </ul>

        {reel.analogy && (
          <div className="bg-white/10 border-2 border-[#f5a623] rounded-xl p-3 mb-3">
            <p className="text-[9px] uppercase tracking-[0.3em] text-[#f5a623] mb-1 font-semibold">Analogy</p>
            <p className="text-white/95 text-xs italic leading-relaxed">{reel.analogy}</p>
          </div>
        )}

        <div className="mb-3">
          <span className="inline-block px-4 py-1.5 rounded-full bg-[#00c4cc] text-[#0a0a0f] font-semibold text-xs">
            ✓ {reel.takeaway}
          </span>
        </div>

        {/* Progress dots */}
        <div className="flex items-center justify-center gap-1.5 mb-3">
          {Array.from({ length: total }).map((_, k) => (
            <div
              key={k}
              className={`h-1.5 rounded-full transition-all ${k === idx ? "w-6 bg-white" : "w-1.5 bg-white/40"}`}
            />
          ))}
        </div>

        <button
          onClick={onShare}
          data-testid={`reel-share-${idx}`}
          className="w-full py-3 rounded-xl bg-white text-[#0a0a0f] font-medium hover:bg-white/90 transition flex items-center justify-center gap-2"
        >
          <Share2 className="w-4 h-4" /> Share to WhatsApp
        </button>
      </div>
    </div>
  );
}
